# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99856680c55fe5d8168efc337f470b2fa0d5a72ddc1faeed78e549d810e4426bfa1ebee4a84e914024e69a1d90b343c837c91ce27da037db9ca36d43f5c672be

test:
  secret_key_base: 58b56a9351137acd447f81bd4c1110602a85c9b2a7d2d7fbd1d8154a8869dde6fe68727ceaa8142ad5c86f513b59c91a2acd6228d6cf63c73c1a4ae8cac1de99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
